services:
  - type: web
    name: escuelaparapadres-backend
    env: node
    region: oregon
    plan: free
    branch: feature/mobile-functionality
    buildCommand: npm ci --include=dev && npm run build
    startCommand: cd build && npm ci --omit=dev && node bin/server.js
    healthCheckPath: /api/movil/soporte/info
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_KEY
        value: ZsSyLQ0bAilrP5mWD9rGaaHLogmkqO1l
      - key: JWT_SECRET
        value: c291702bdb4749589d66b58423fd8d3da86941638adc8fd75b1ec3ab9a6bd0a3
      - key: LOG_LEVEL
        value: info
      - key: APP_NAME
        value: ESCUELAPARAPADRES