-- Script completo para configurar la base de datos en Supabase

CREATE TABLE IF NOT EXISTS public.departamentos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL UNIQUE,
  codigo character varying UNIQUE
);

CREATE TABLE IF NOT EXISTS public.municipios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL,
  departamento_id integer NOT NULL,
  codigo character varying UNIQUE,
  CONSTRAINT municipios_departamento_id_fkey
    FOREIGN KEY (departamento_id) REFERENCES public.departamentos(id)
);

CREATE TABLE IF NOT EXISTS public.instituciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL,
  telefono character varying,
  correo character varying,
  direccion character varying,
  naturaleza text NOT NULL,
  municipio_id integer NOT NULL,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eliminado_en timestamp without time zone,
  CONSTRAINT instituciones_municipio_id_fkey
    FOREIGN KEY (municipio_id) REFERENCES public.municipios(id)
);

CREATE TABLE IF NOT EXISTS public.grados (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL UNIQUE,
  orden integer
);

CREATE TABLE IF NOT EXISTS public.roles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL UNIQUE,
  esta_activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.usuarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  correo character varying NOT NULL UNIQUE,
  contrasena_hash character varying NOT NULL,
  esta_activo boolean NOT NULL DEFAULT true,
  debe_cambiar_contrasena boolean NOT NULL DEFAULT false,
  token_fcm character varying,
  ultimo_ingreso timestamp without time zone,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eliminado_en timestamp without time zone,
  rol_id integer NOT NULL,
  CONSTRAINT usuarios_rol_id_fkey
    FOREIGN KEY (rol_id) REFERENCES public.roles(id)
);

CREATE TABLE IF NOT EXISTS public.cursos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL,
  grado_id integer NOT NULL,
  jornada text NOT NULL,
  institucion_id integer NOT NULL,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cursos_grado_id_fkey
    FOREIGN KEY (grado_id) REFERENCES public.grados(id),
  CONSTRAINT cursos_institucion_id_fkey
    FOREIGN KEY (institucion_id) REFERENCES public.instituciones(id)
);

CREATE TABLE IF NOT EXISTS public.categorias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL UNIQUE,
  descripcion text,
  color character varying,
  icono character varying
);

CREATE TABLE IF NOT EXISTS public.periodos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre character varying NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  institucion_id integer NOT NULL,
  esta_activo boolean NOT NULL DEFAULT false,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT periodos_institucion_id_fkey
    FOREIGN KEY (institucion_id) REFERENCES public.instituciones(id)
);

-- =========================
-- PERSONAS
-- =========================

CREATE TABLE IF NOT EXISTS public.docentes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombres character varying NOT NULL,
  apellidos character varying NOT NULL,
  tipo_documento text NOT NULL,
  numero_documento character varying NOT NULL UNIQUE,
  telefono character varying NOT NULL,
  telefono_emergencia character varying,
  persona_emergencia character varying,
  correo character varying NOT NULL,
  direccion character varying,
  es_director_grado boolean NOT NULL DEFAULT false,
  grado_asignado integer,
  area_que_orienta character varying,
  centro_interes character varying,
  institucion_id integer NOT NULL,
  usuario_id integer NOT NULL,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eliminado_en timestamp without time zone,
  CONSTRAINT docentes_grado_asignado_fkey
    FOREIGN KEY (grado_asignado) REFERENCES public.grados(id),
  CONSTRAINT docentes_institucion_id_fkey
    FOREIGN KEY (institucion_id) REFERENCES public.instituciones(id),
  CONSTRAINT docentes_usuario_id_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE TABLE IF NOT EXISTS public.acudientes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombres character varying NOT NULL,
  apellidos character varying NOT NULL,
  tipo_documento text NOT NULL,
  numero_documento character varying NOT NULL UNIQUE,
  telefono character varying NOT NULL,
  telefono_alternativo character varying,
  correo character varying,
  direccion character varying,
  parentesco text,
  ocupacion character varying,
  tipo_trabajo text,
  nivel_educativo text,
  aporta_economia boolean,
  horario_trabajo character varying,
  usuario_id integer NOT NULL,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eliminado_en timestamp without time zone,
  CONSTRAINT acudientes_usuario_id_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE TABLE IF NOT EXISTS public.estudiantes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombres character varying NOT NULL,
  apellidos character varying NOT NULL,
  tipo_documento text NOT NULL,
  numero_documento character varying NOT NULL UNIQUE,
  fecha_nacimiento date NOT NULL,
  sexo text NOT NULL,
  grupo_sanguineo text,
  rh text,
  pais_nacimiento character varying,
  ciudad_nacimiento character varying,
  estrato smallint CHECK (estrato >= 1 AND estrato <= 6),
  etnia character varying,
  eps character varying,
  curso_id integer NOT NULL,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eliminado_en timestamp without time zone,
  CONSTRAINT estudiantes_curso_id_fkey
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
);

-- =========================
-- BANCO DE TAREAS / ASIGNACIONES
-- =========================

CREATE TABLE IF NOT EXISTS public.banco_tareas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo character varying NOT NULL,
  descripcion text NOT NULL,
  enlace character varying,
  categoria_id integer NOT NULL,
  creado_por integer,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tema character varying,
  entregable_esperado text,
  grados_objetivo jsonb,
  es_multi_grado boolean NOT NULL DEFAULT false,
  tipo_calificacion text NOT NULL DEFAULT 'manual',
  criterios_automaticos jsonb,
  veces_utilizada integer NOT NULL DEFAULT 0,
  CONSTRAINT banco_tareas_categoria_id_fkey
    FOREIGN KEY (categoria_id) REFERENCES public.categorias(id),
  CONSTRAINT banco_tareas_creado_por_fkey
    FOREIGN KEY (creado_por) REFERENCES public.usuarios(id)
);

CREATE TABLE IF NOT EXISTS public.asignaciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo character varying NOT NULL,
  descripcion text NOT NULL,
  frecuencia text NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_vencimiento date,
  incluir_en_boletin boolean NOT NULL DEFAULT true,
  curso_id integer,
  docente_id integer NOT NULL,
  categoria_id integer,
  banco_tarea_id integer,
  periodo_id integer NOT NULL,
  institucion_id integer,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tema character varying,
  CONSTRAINT asignaciones_curso_id_fkey
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id),
  CONSTRAINT asignaciones_docente_id_fkey
    FOREIGN KEY (docente_id) REFERENCES public.docentes(id),
  CONSTRAINT asignaciones_categoria_id_fkey
    FOREIGN KEY (categoria_id) REFERENCES public.categorias(id),
  CONSTRAINT asignaciones_banco_tarea_id_fkey
    FOREIGN KEY (banco_tarea_id) REFERENCES public.banco_tareas(id),
  CONSTRAINT asignaciones_periodo_id_fkey
    FOREIGN KEY (periodo_id) REFERENCES public.periodos(id)
);

-- =========================
-- PIVOTES
-- =========================

CREATE TABLE IF NOT EXISTS public.docente_curso (
  docente_id integer NOT NULL,
  curso_id integer NOT NULL,
  es_director boolean NOT NULL DEFAULT false,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT docente_curso_pkey PRIMARY KEY (docente_id, curso_id),
  CONSTRAINT docente_curso_docente_id_fkey
    FOREIGN KEY (docente_id) REFERENCES public.docentes(id),
  CONSTRAINT docente_curso_curso_id_fkey
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
);

CREATE TABLE IF NOT EXISTS public.estudiante_acudiente (
  estudiante_id integer NOT NULL,
  acudiente_id integer NOT NULL,
  relacion text NOT NULL,
  es_principal boolean NOT NULL DEFAULT false,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT estudiante_acudiente_pkey PRIMARY KEY (estudiante_id, acudiente_id),
  CONSTRAINT estudiante_acudiente_estudiante_id_fkey
    FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id),
  CONSTRAINT estudiante_acudiente_acudiente_id_fkey
    FOREIGN KEY (acudiente_id) REFERENCES public.acudientes(id)
);

CREATE TABLE IF NOT EXISTS public.asignacion_cursos (
  asignacion_id integer NOT NULL,
  curso_id integer NOT NULL,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT asignacion_cursos_pkey PRIMARY KEY (asignacion_id, curso_id),
  CONSTRAINT asignacion_cursos_asignacion_id_fkey
    FOREIGN KEY (asignacion_id) REFERENCES public.asignaciones(id),
  CONSTRAINT asignacion_cursos_curso_id_fkey
    FOREIGN KEY (curso_id) REFERENCES public.cursos(id)
);

-- =========================
-- ENTREGAS / CALIFICACIONES / NOTIFICACIONES / AUDITORIA
-- =========================

CREATE TABLE IF NOT EXISTS public.entregas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asignacion_id integer NOT NULL,
  estudiante_id integer NOT NULL,
  acudiente_id integer NOT NULL,
  evidencia_texto text,
  archivos_url jsonb,
  fecha_entrega timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado text NOT NULL DEFAULT 'enviada',
  institucion_id integer,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  nombre_envio character varying,
  CONSTRAINT entregas_asignacion_id_fkey
    FOREIGN KEY (asignacion_id) REFERENCES public.asignaciones(id),
  CONSTRAINT entregas_estudiante_id_fkey
    FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id),
  CONSTRAINT entregas_acudiente_id_fkey
    FOREIGN KEY (acudiente_id) REFERENCES public.acudientes(id)
);

CREATE TABLE IF NOT EXISTS public.calificaciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entrega_id integer NOT NULL UNIQUE,
  estudiante_id integer NOT NULL,
  asignacion_id integer NOT NULL,
  nota numeric CHECK (nota IS NULL OR nota >= 0.0 AND nota <= 5.0),
  escala text NOT NULL,
  nota_cualitativa text,
  retroalimentacion text,
  calificado_por integer NOT NULL,
  calificado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  periodo_id integer NOT NULL,
  institucion_id integer,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  es_automatica boolean NOT NULL DEFAULT false,
  CONSTRAINT calificaciones_entrega_id_fkey
    FOREIGN KEY (entrega_id) REFERENCES public.entregas(id),
  CONSTRAINT calificaciones_estudiante_id_fkey
    FOREIGN KEY (estudiante_id) REFERENCES public.estudiantes(id),
  CONSTRAINT calificaciones_asignacion_id_fkey
    FOREIGN KEY (asignacion_id) REFERENCES public.asignaciones(id),
  CONSTRAINT calificaciones_calificado_por_fkey
    FOREIGN KEY (calificado_por) REFERENCES public.docentes(id),
  CONSTRAINT calificaciones_periodo_id_fkey
    FOREIGN KEY (periodo_id) REFERENCES public.periodos(id)
);

CREATE TABLE IF NOT EXISTS public.notificaciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destinatario_id integer NOT NULL,
  tipo text NOT NULL,
  asunto character varying,
  mensaje text NOT NULL,
  estado text NOT NULL DEFAULT 'pendiente',
  enviado_en timestamp without time zone,
  leido_en timestamp without time zone,
  asignacion_id integer,
  metadatos jsonb,
  institucion_id integer,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT notificaciones_destinatario_id_fkey
    FOREIGN KEY (destinatario_id) REFERENCES public.usuarios(id),
  CONSTRAINT notificaciones_asignacion_id_fkey
    FOREIGN KEY (asignacion_id) REFERENCES public.asignaciones(id)
);

CREATE TABLE IF NOT EXISTS public.auditoria (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer,
  accion text NOT NULL,
  entidad character varying NOT NULL,
  entidad_id integer NOT NULL,
  cambios_json jsonb,
  direccion_ip character varying,
  agente_usuario character varying,
  institucion_id integer,
  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT auditoria_usuario_id_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

-- =========================
-- PATCH: instituciones (agregar columnas nuevas)
-- =========================

ALTER TABLE public.instituciones
  ADD COLUMN IF NOT EXISTS codigo_dane character varying(20),
  ADD COLUMN IF NOT EXISTS nit character varying(20),
  ADD COLUMN IF NOT EXISTS resolucion_aprobacion character varying(100),
  ADD COLUMN IF NOT EXISTS niveles_educativos jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS modalidad character varying(20) DEFAULT 'presencial'::character varying,
  ADD COLUMN IF NOT EXISTS jornadas jsonb DEFAULT '["unica"]'::jsonb,
  ADD COLUMN IF NOT EXISTS telefono_principal character varying(20) NOT NULL DEFAULT ''::character varying,
  ADD COLUMN IF NOT EXISTS telefono_secretaria character varying(20),
  ADD COLUMN IF NOT EXISTS correo_institucional character varying(255) NOT NULL DEFAULT ''::character varying,
  ADD COLUMN IF NOT EXISTS correo_rectoria character varying(255),
  ADD COLUMN IF NOT EXISTS sitio_web character varying(255),
  ADD COLUMN IF NOT EXISTS direccion_completa text,
  ADD COLUMN IF NOT EXISTS barrio character varying(100),
  ADD COLUMN IF NOT EXISTS estrato smallint,
  ADD COLUMN IF NOT EXISTS coordenadas_gps character varying(50),
  ADD COLUMN IF NOT EXISTS capacidad_estudiantes integer,
  ADD COLUMN IF NOT EXISTS ano_fundacion integer,
  ADD COLUMN IF NOT EXISTS enfoque_pedagogico character varying(100),
  ADD COLUMN IF NOT EXISTS confesional boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS religion character varying(50),
  ADD COLUMN IF NOT EXISTS rector_nombre character varying(255),
  ADD COLUMN IF NOT EXISTS rector_documento character varying(20),
  ADD COLUMN IF NOT EXISTS rector_telefono character varying(20),
  ADD COLUMN IF NOT EXISTS rector_correo character varying(255);

-- Uniques (solo si no existen). OJO: en Postgres no existe "ADD CONSTRAINT IF NOT EXISTS" en todas las versiones,
-- entonces lo manejamos con DO $$.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'instituciones_codigo_dane_key'
  ) THEN
    ALTER TABLE public.instituciones
      ADD CONSTRAINT instituciones_codigo_dane_key UNIQUE (codigo_dane);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'instituciones_nit_key'
  ) THEN
    ALTER TABLE public.instituciones
      ADD CONSTRAINT instituciones_nit_key UNIQUE (nit);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'instituciones_estrato_check'
  ) THEN
    ALTER TABLE public.instituciones
      ADD CONSTRAINT instituciones_estrato_check CHECK (estrato >= 1 AND estrato <= 6);
  END IF;
END$$;

-- Índices
CREATE INDEX IF NOT EXISTS idx_instituciones_codigo_dane ON public.instituciones (codigo_dane);
CREATE INDEX IF NOT EXISTS idx_instituciones_nit ON public.instituciones (nit);
CREATE INDEX IF NOT EXISTS idx_instituciones_estrato ON public.instituciones (estrato);
CREATE INDEX IF NOT EXISTS idx_instituciones_municipio ON public.instituciones (municipio_id);

-- =========================
-- NUEVA TABLA: funcionarios
-- =========================

CREATE TABLE IF NOT EXISTS public.funcionarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  nombre character varying(255) NOT NULL,
  apellido character varying(255) NOT NULL,
  telefono character varying(20),
  correo_institucional character varying(255),
  direccion character varying(255),

  rol_id integer NOT NULL,
  usuario_id integer NOT NULL,
  institucion_id integer NULL,

  creado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  eliminado_en timestamp without time zone NULL,

  CONSTRAINT funcionarios_rol_id_fkey
    FOREIGN KEY (rol_id) REFERENCES public.roles(id) ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT funcionarios_usuario_id_fkey
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT funcionarios_institucion_id_fkey
    FOREIGN KEY (institucion_id) REFERENCES public.instituciones(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 1:1 usuario <-> funcionario
CREATE UNIQUE INDEX IF NOT EXISTS funcionarios_usuario_id_unique ON public.funcionarios (usuario_id);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_funcionarios_rol ON public.funcionarios (rol_id);
CREATE INDEX IF NOT EXISTS idx_funcionarios_institucion ON public.funcionarios (institucion_id);

ALTER TABLE usuarios
  ALTER COLUMN contrasena_hash TYPE text;
